### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_sudoku'

### ISSUE THREAD

**Issue by skipperkongen** [artonge/gym-sudoku#1]
$ uname
Darwin

$ python --version
Python 3.6.5 :: Anaconda, Inc.

$ pip list | grep sudoku
gym-sudoku                         1.0.2

$ python -c "import gym_sudoku"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gym_sudoku'

**Comment by artonge** [comment]
Hi, I won't be able to look into this issue until October the first. Thanks for reporting !

**Comment by skipperkongen** [comment]
No worries. Thanks!

**Comment by VietAnhDao** [comment]
is there an update on this issue?

**Comment by artonge** [comment]
Can you test and tell me if it's fixed ?

**Comment by VietAnhDao** [comment]
yep, the module is now properly imported.
